import os, subprocess

BASE = r'C:\Users\jxgm\Documents\New project'

with open(os.path.join(BASE, 'app.js.bak'), 'r', encoding='utf-8') as f:
    base = f.read()

# Build FP module
fp = []
fp.append('  var DEVICE_FP_KEY = "murmur_device_fp_v3";')
fp.append('  var DEVICE_ACC_KEY = "murmur_device_account_v3";')
fp.append('  var deviceFingerprint = "";')
fp.append('  var deviceAccount = null;')
fp.append('  async function generateDeviceFingerprint() {')
fp.append('    var parts = [];')
fp.append("    parts.push(navigator.userAgent);")
fp.append("    parts.push(screen.width + 'x' + screen.height);")
fp.append("    parts.push(screen.colorDepth + 'bit');")
fp.append("    parts.push(navigator.language);")
fp.append("    parts.push(Intl.DateTimeFormat().resolvedOptions().timeZone);")
fp.append("    parts.push(new Date().getTimezoneOffset());")
fp.append("    try { parts.push(navigator.hardwareConcurrency || ''); } catch(e) {}")
fp.append("    try { parts.push(navigator.deviceMemory || ''); } catch(e) {}")
fp.append("    try {")
fp.append("      var canvas = document.createElement('canvas');")
fp.append('      var ctx = canvas.getContext("2d");')
fp.append('      ctx.textBaseline = "top"; ctx.font = "14px Arial";')
fp.append("      ctx.fillText('DeviceFP', 2, 2);")
fp.append('      parts.push(canvas.toDataURL().substring(0, 500));')
fp.append('    } catch(e) {}')
fp.append('    try {')
fp.append('      var gl = canvas.getContext("webgl") || canvas.getContext("experimental-webgl");')
fp.append('      if (gl) {')
fp.append('        var ext = gl.getExtension("WEBGL_debug_renderer_info");')
fp.append("        if (ext) { parts.push(gl.getParameter(ext.UNMASKED_RENDERER_WEBGL)); parts.push(gl.getParameter(ext.UNMASKED_VENDOR_WEBGL)); }")
fp.append('      }')
fp.append('    } catch(e) {}')
fp.append("    var combined = parts.join('|');")
fp.append("    var hash = await crypto.subtle.digest('SHA-256', enc.encode(combined));")
fp.append("    return Array.from(new Uint8Array(hash)).map(function(b){return b.toString(16).padStart(2,'0')}).join('').substring(0, 32);")
fp.append('  }')
fp.append('  async function getOrCreateDeviceAccount() {')
fp.append('    var stored = localStorage.getItem(DEVICE_ACC_KEY);')
fp.append('    if (stored) { try { deviceAccount = JSON.parse(stored); return deviceAccount; } catch(e) {} }')
fp.append('    var fp2 = await generateDeviceFingerprint();')
fp.append('    deviceFingerprint = fp2;')
fp.append('    deviceAccount = { id: fp2.substring(0, 16), fingerprint: fp2, createdAt: Date.now(), lastSeen: Date.now() };')
fp.append('    localStorage.setItem(DEVICE_ACC_KEY, JSON.stringify(deviceAccount));')
fp.append('    localStorage.setItem(DEVICE_FP_KEY, fp2);')
fp.append('    return deviceAccount;')
fp.append('  }')
fp.append('  function updateDeviceLastSeen() {')
fp.append('    if (deviceAccount) { deviceAccount.lastSeen = Date.now(); localStorage.setItem(DEVICE_ACC_KEY, JSON.stringify(deviceAccount)); }')
fp.append('  }')
fp_mod = chr(10).join(fp)

# Build DB module
db = []
db.append('  var DB_NAME = "MurmurEncryptedDB";')
db.append('  var DB_VERSION = 2;')
db.append('  var dbInstance = null;')
db.append('  var LOCAL_DB_RETENTION_MS = 7 * 24 * 60 * 60 * 1000;')
db.append('  async function openLocalDB() {')
db.append('    if (dbInstance) return dbInstance;')
db.append('    return new Promise(function(resolve, reject) {')
db.append('      var request = indexedDB.open(DB_NAME, DB_VERSION);')
db.append('      request.onupgradeneeded = function(e) {')
db.append('        var db = e.target.result;')
db.append("        if (!db.objectStoreNames.contains('messages')) {")
db.append("          var ms = db.createObjectStore('messages', { keyPath: 'id' });")
db.append("          ms.createIndex('room', 'room', { unique: false });")
db.append("          ms.createIndex('timestamp', 'timestamp', { unique: false });")
db.append("          ms.createIndex('expiresAt', 'expiresAt', { unique: false });")
db.append('        }')
db.append("        if (!db.objectStoreNames.contains('files')) {")
db.append("          var fs2 = db.createObjectStore('files', { keyPath: 'id' });")
db.append("          fs2.createIndex('room', 'room', { unique: false });")
db.append("          fs2.createIndex('expiresAt', 'expiresAt', { unique: false });")
db.append('        }')
db.append("        if (!db.objectStoreNames.contains('contacts')) {")
db.append("          db.createObjectStore('contacts', { keyPath: 'id' });")
db.append('        }')
db.append('      };')
db.append('      request.onsuccess = function(e) { dbInstance = e.target.result; resolve(dbInstance); };')
db.append('      request.onerror = function(e) { reject(e); };')
db.append('    });')
db.append('  }')
db.append('  function nowWithTTL() { return { timestamp: Date.now(), expiresAt: Date.now() + LOCAL_DB_RETENTION_MS }; }')
db.append('  async function storeEncryptedMessage(room, encryptedData, direction) {')
db.append('    var db2 = await openLocalDB();')
db.append('    return new Promise(function(resolve, reject) {')
db.append("      var tx = db2.transaction('messages', 'readwrite');")
db.append("      var store = tx.objectStore('messages');")
db.append("      var record = { id: 'msg_' + room + '_' + Date.now() + '_' + Math.random().toString(36).substring(2, 8), room: room, encryptedData: encryptedData, direction: direction || 'both', type: 'message', size: encryptedData.length || 0, deviceAccount: deviceAccount ? deviceAccount.id : '' };")
db.append('      Object.assign(record, nowWithTTL());')
db.append('      store.add(record);')
db.append('      tx.oncomplete = function() { resolve(record.id); };')
db.append('      tx.onerror = function(e) { reject(e); };')
db.append('    });')
db.append('  }')
db.append('  async function storeEncryptedFile(room, fileInfo) {')
db.append('    var db2 = await openLocalDB();')
db.append('    return new Promise(function(resolve, reject) {')
db.append("      var tx = db2.transaction('files', 'readwrite');")
db.append("      var store = tx.objectStore('files');")
db.append("      var record = { id: 'file_' + room + '_' + Date.now() + '_' + Math.random().toString(36).substring(2, 8), room: room, fileInfo: fileInfo, type: 'file', deviceAccount: deviceAccount ? deviceAccount.id : '' };")
db.append('      Object.assign(record, nowWithTTL());')
db.append('      store.add(record);')
db.append('      tx.oncomplete = function() { resolve(record.id); };')
db.append('      tx.onerror = function(e) { reject(e); };')
db.append('    });')
db.append('  }')
db.append('  async function getMessagesByRoom(room, limit) {')
db.append('    limit = limit || 200;')
db.append('    var db2 = await openLocalDB();')
db.append('    return new Promise(function(resolve, reject) {')
db.append("      var tx = db2.transaction('messages', 'readonly');")
db.append("      var store = tx.objectStore('messages');")
db.append("      var index = store.index('room');")
db.append('      var request = index.getAll(room);')
db.append('      request.onsuccess = function() {')
db.append("        var all = (request.result || []).filter(function(m) { return m.expiresAt > Date.now(); });")
db.append('        all.sort(function(a, b) { return (b.timestamp || 0) - (a.timestamp || 0); });')
db.append('        resolve(all.slice(0, limit));')
db.append('      };')
db.append('      request.onerror = function(e) { reject(e); };')
db.append('    });')
db.append('  }')
db.append('  async function cleanupExpiredRecords() {')
db.append('    var db2 = await openLocalDB();')
db.append('    var now = Date.now();')
db.append('    var cleanCount = 0;')
db.append("    var tx1 = db2.transaction('messages', 'readwrite');")
db.append("    var store1 = tx1.objectStore('messages');")
db.append("    var index1 = store1.index('expiresAt');")
db.append('    var req1 = index1.openCursor(IDBKeyRange.upperBound(now));')
db.append('    req1.onsuccess = function(e) { var c = e.target.result; if (c) { c.delete(); cleanCount++; c.continue(); } };')
db.append("    var tx2 = db2.transaction('files', 'readwrite');")
db.append("    var store2 = tx2.objectStore('files');")
db.append("    var index2 = store2.index('expiresAt');")
db.append('    var req2 = index2.openCursor(IDBKeyRange.upperBound(now));')
db.append('    req2.onsuccess = function(e) { var c = e.target.result; if (c) { c.delete(); cleanCount++; c.continue(); } };')
db.append("    tx2.oncomplete = function() { if (cleanCount > 0) showToast('已清理 ' + cleanCount + ' 条过期记录'); };")
db.append('  }')
db_mod = chr(10).join(db)

# Build security module
sec = []
sec.append('  var SCREEN_CAPTURE_DETECTED = false;')
sec.append('  var DEVTOOLS_DETECTED = false;')
sec.append('  function enableAntiScreenshotProtections() {')
sec.append("    document.addEventListener('copy', function(e) { e.preventDefault(); showToast('复制已禁用'); return false; }, true);")
sec.append("    document.addEventListener('cut', function(e) { e.preventDefault(); showToast('剪切已禁用'); return false; }, true);")
sec.append("    document.addEventListener('paste', function(e) { e.preventDefault(); showToast('粘贴已禁用'); return false; }, true);")
sec.append("    document.addEventListener('contextmenu', function(e) { e.preventDefault(); showToast('右键菜单已禁用'); return false; }, true);")
sec.append("    document.addEventListener('keydown', function(e) {")
sec.append("      if ((e.ctrlKey || e.metaKey) && (e.key === 'c' || e.key === 'C')) { e.preventDefault(); showToast('复制已禁用'); return false; }")
sec.append("      if (e.key === 'PrintScreen') { e.preventDefault(); showToast('截屏已禁用'); return false; }")
sec.append("      if (e.key === 'F12') { e.preventDefault(); return false; }")
sec.append('    }, true);')
sec.append("    var style = document.createElement('style');")
sec.append("    style.textContent = '* { -webkit-user-select: none !important; user-select: none !important; -webkit-touch-callout: none !important; } textarea, input { -webkit-user-select: text !important; user-select: text !important; }';")
sec.append('    document.head.appendChild(style);')
sec.append("    document.addEventListener('visibilitychange', function() {")
sec.append("      if (document.visibilityState === 'hidden') { sendPayload({ type: 'privacy-alert', alert: 'screen-away' }); }")
sec.append('    });')
sec.append('    var devtoolsChecker = function() {')
sec.append('      var t = 160;')
sec.append('      var wd = window.outerWidth - window.innerWidth > t;')
sec.append('      var hd = window.outerHeight - window.innerHeight > t;')
sec.append("      if (wd || hd) { if (!DEVTOOLS_DETECTED) { DEVTOOLS_DETECTED = true; showToast('检测到开发者工具'); sendPayload({ type: 'privacy-alert', alert: 'devtools-open' }); } }")
sec.append('      else { DEVTOOLS_DETECTED = false; }')
sec.append('    };')
sec.append('    setInterval(devtoolsChecker, 2000);')
sec.append('  }')
sec.append('  function enableScreenCaptureDetection() {')
sec.append('    if (navigator.mediaDevices && navigator.mediaDevices.getUserMedia) {')
sec.append('      var origUGM = navigator.mediaDevices.getUserMedia.bind(navigator.mediaDevices);')
sec.append('      navigator.mediaDevices.getUserMedia = function(constraints) {')
sec.append('        if (constraints.video && constraints.video.displaySurface) {')
sec.append('          SCREEN_CAPTURE_DETECTED = true;')
sec.append("          showToast('检测到屏幕录制，已向对方发出警告');")
sec.append("          sendPayload({ type: 'privacy-alert', alert: 'screen-recording' });")
sec.append('          showRecordingWarningOverlay();')
sec.append('        }')
sec.append('        return origUGM(constraints);')
sec.append('      };')
sec.append('    }')
sec.append("    document.addEventListener('fullscreenchange', function() {")
sec.append("      if (document.fullscreenElement) { sendPayload({ type: 'privacy-alert', alert: 'fullscreen' }); }")
sec.append('    });')
sec.append('  }')
sec.append('  function showRecordingWarningOverlay() {')
sec.append('    var overlay = document.getElementById("recordingWarningOverlay");')
sec.append('    if (!overlay) {')
sec.append('      overlay = document.createElement("div");')
sec.append('      overlay.id = "recordingWarningOverlay";')
sec.append('      overlay.style.cssText = "position:fixed;top:0;left:0;right:0;bottom:0;z-index:9999;background:rgba(255,55,55,0.08);pointer-events:none;display:flex;align-items:center;justify-content:center;";')
sec.append("      overlay.innerHTML = '<div style=\"background:rgba(255,55,55,0.95);color:white;padding:20px 40px;border-radius:20px;font-size:18px;font-weight:700;text-align:center;\">\\u26a0\\ufe0f 检测到屏幕录制\\n对方已收到通知</div>';")
sec.append('      document.body.appendChild(overlay);')
sec.append('    }')
sec.append('    overlay.hidden = false;')
sec.append('    setTimeout(function() { if (overlay) overlay.hidden = true; }, 4000);')
sec.append('  }')
sec_mod = chr(10).join(sec)

# Insert device init before makeKeyPair call
init_block = """
  // DEVICE ACCOUNT INIT
  getOrCreateDeviceAccount().then(function() {
    updateDeviceLastSeen();
    cleanupExpiredRecords();
    enableAntiScreenshotProtections();
    enableScreenCaptureDetection();
    if (!roomId) { showLobby(); } else { connectEvents(); }
  });
"""

base = base.replace('makeKeyPair().then(connectEvents)', init_block + 'makeKeyPair().then(connectEvents)')

# Append modules before closing IIFE
close_pos = base.rindex('})();')
result = base[:close_pos] + chr(10)*2 + fp_mod + chr(10)*2 + db_mod + chr(10)*2 + sec_mod + chr(10)*2 + '})();' + chr(10)

with open(os.path.join(BASE, 'app.js'), 'w', encoding='utf-8') as f:
    f.write(result)

print('Built: %d chars, %d lines' % (len(result), result.count(chr(10))))

# Verify with acorn
ret = subprocess.run(['node', '-e',
    "const acorn=require('acorn'); const fs=require('fs');"
    " const code=fs.readFileSync('C:/Users/jxgm/Documents/New project/app.js','utf8');"
    " try{acorn.parse(code,{ecmaVersion:2024,sourceType:'module'}); console.log('SYNTAX OK');"
    " }catch(e){console.log('SYNTAX ERR:',e.message);}"
], capture_output=True, text=True, cwd=os.path.join(BASE))
print('Acorn:', ret.stdout.strip() or ret.stderr.strip())
