# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously interfering flutter
# permissions help
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings target
  end
end
